AtomicFox556/Cataclysm-EOD

README.md
None
Test commit to see if my current setup works.
=> Rename DDA to EOD

data/json/items/comestibles/drink.json, data/json/recipes/recipe_medsandchemicals.json
=> Fix JSON errors

data/raw/keybindings.json, src/debug_menu.cpp, src/diary.h, src/newcharacter.cpp, src/player_display.cpp
Interface "Rename gender to sex"
Rename gender to sex, as it's more likely to be relevant for game purposes than the character's self-perception (such as gender) and also avoids stating anything on the issue of whether gender is changeable or not. Profession change also got moved to character customization menu, in place of gender change.
Sex is now changeable via a debug menu.
Compiled game, checked that "gender" got changed to "sex" on character creation screen and that sex change via debug menu works as intended.
=> Rename gender to sex

README.md, doc/CONTRIBUTING.md
None
Edit more docs to reflect the new name of the fork, add a link to a Discord server of the fork.
=> Update more docs

data/json/items/armor/cloaks.json
Bugfixes "Fix flag description"
Fix a mismatch between one flag variant's name and its description.
=> Fix flag description

data/core/game_balance.json, data/json/EraOfDecay/effects.json, data/json/EraOfDecay/items/comestibles/med.json, src/activity_actor.cpp, src/activity_handlers.cpp, src/activity_tracker.cpp, src/character.cpp, src/consumption.cpp, src/crafting.cpp, src/item.cpp, src/iuse.cpp, src/options.cpp, src/ranged.cpp, src/recipe.cpp, src/recipe.h, src/suffer.cpp, src/timed_event.cpp, src/trapfunc.cpp, src/vehicle.cpp
Features "Adjustable balance settings"
Initial implementation of adjustable balance settings. Adjustable via options now are wildlife density, vitamins, hunger, thirst, fatigue, stamina, weariness, heal speed, diseases, gun dispersion, crafting time, and proficiencies.
This is only an initial implementation; later on, more game mechanics and their more specific aspects will become adjustable like that.
I probably should figure out how to JSONize individual settings at some point while still having them adjustable without manual file editing.
=> Adjustable balance settings implementation

.github/workflows/push-translation-template.yml, .github/workflows/release.yml
Build "Enable autoreleases"
Try to enable autoreleases for EOD, code sourced from https://github.com/CleverRaven/Cataclysm-DDA/pull/62696 by @GeekDuanLian.
=> Enable autoreleases

tests/stomach_contents_test.cpp, tests/submap_load_test.cpp, tests/weary_test.cpp
=> Fix more tests

data/json/EraOfDecay/flags.json, data/json/items/armor/power_armor.json, src/flag.cpp, src/flag.h, src/item.cpp, src/item.h
Bugfixes "Power armor bugfix"
Fix a power armor bug while power armor hauling frames caused errors and didn't work correctly.
=> Power armor fix

data/json/EraOfDecay/items/armor/hats.json, data/json/EraOfDecay/items/armor/hoods.json, data/json/EraOfDecay/items/armor/storage.json, data/json/EraOfDecay/recipes/armor/head.json, data/json/EraOfDecay/recipes/armor/storage.json, data/json/items/armor/hoods.json, data/json/items/armor/storage.json, data/json/items/containers.json, data/json/recipes/armor/head.json, data/json/recipes/armor/storage.json
Content "Add more wearable gear"
Add more wearable gear, including wearable liquid containers, plastic rain hood and a paper hat.
=> Add more wearable gear

data/json/EraOfDecay/recipes/chem/chemicals.json, data/json/EraOfDecay/recipes/other/materials.json
=> Format fix

doc/JSON_INFO.md, src/item_category.cpp, src/item_category.h, src/map.cpp, src/options.cpp
Features "Port options for item category spawn rate"
A port of https://github.com/CleverRaven/Cataclysm-DDA/pull/64586, originally by @Night-Pryanik.
=> Port options for item category spawn rate

.github/workflows/msvc-full-features.yml, .github/workflows/release.yml, src/cached_options.cpp, src/cached_options.h, src/character.cpp, src/descriptions.cpp, src/game.cpp, src/item.cpp, src/melee.cpp, src/monster.cpp, src/options.cpp
Features "Port minor changes from TISH fork"
Port the following changes:
https://github.com/Cataclysm-TISH-team/Cataclysm-TISH/pull/11
https://github.com/Cataclysm-TISH-team/Cataclysm-TISH/pull/9
https://github.com/Cataclysm-TISH-team/Cataclysm-TISH/pull/7
https://github.com/Cataclysm-TISH-team/Cataclysm-TISH/pull/6
https://github.com/Cataclysm-TISH-team/Cataclysm-TISH/pull/5
=> Port minor changes from TISH fork

.github/workflows/release.yml
=> Try to fix builds again

src/grab.cpp
Features "Allow dragging heavier vehicles"
Increase weight limit for dragging vehicles in certain conditions.
Full list of changes to vehicle dragging:
The default weight limit is now 100 kg per point of strength. This assumes best-case scenario of four wheels (or a set of casters, such as a shopping cart) and a flat hard surface such as a road. Worst-case scenario is now 10 kg per point of strength, assuming either a vehicle with no wheels, or with wheels totally unsuitable for off-roading and moving on off-road terrain. This means that average characters can now push 800 kg vehicles in best case scenario, and 80 kg vehicles in worst case scenario.
Absolute draggable vehicle weight limit (regardless of player strength) was removed; APCs could now be dragged as well if you managed to get …
=> Allow dragging heavier vehicles

data/json/EraOfDecay/item_category.json, data/json/EraOfDecay/loot_zones.json, data/json/items/book/abstract.json, data/mods/No_Portal_Storms/modinfo.json, src/character.cpp, src/options.cpp, tests/char_healing_test.cpp, tests/memorial_test.cpp, tests/sun_test.cpp
None
Port the following things from TISH fork:
https://github.com/Cataclysm-TISH-team/Cataclysm-TISH/pull/19
https://github.com/Cataclysm-TISH-team/Cataclysm-TISH/pull/29
=> Port more things from TISH fork

src/descriptions.cpp
Features "List deconstruction result types in extended look"
Port https://github.com/cataclysmbnteam/Cataclysm-BN/pull/139 from BN, originally by @Coolthulhu.
=> List deconstruction result types in extended look

data/json/EraOfDecay/recipes/recipe_disassembly.json, data/json/items/armor/cloaks.json
=> Update flags originating from DDA

tools/json_tools/generic_guns_validator.py
=> Update generic guns validator

src/mattack_actors.cpp, tests/mutation_test.cpp
=> Fix code style

.github/workflows/release.yml
=> Try to fix autobuild

src/debug_menu.cpp
Убираю из функции "Quick setup" выдачу мутации "DEBUG_BIONIC_POWERGEN", так как её нету в еод
Ну чтоб не было этой ошибки
Провести слияние
Добавить эту мутацию?
Открыть отладку и нажать на "Quick setup"
Нету
=> Убираем ошибку в отладке

data/json/scenarios.json, data/mods/Standard_Combat_Tests/modinfo.json, data/mods/TEST_DATA/scenarios.json, data/mods/innawood/scenarios.json, data/raw/keybindings.json, doc/JSON_INFO.md, src/calendar_ui.cpp, src/calendar_ui.h, src/debug_menu.cpp, src/game.cpp, src/newcharacter.cpp, src/options.cpp, src/savegame_json.cpp, src/scenario.cpp, src/scenario.h, tests/npc_talk_test.cpp, tests/start_date_test.cpp, tests/stats_tracker_test.cpp
Features "Make start date and Cataclysm date adjustable"
Port relevant changes from DDA that restore the option to select starting date and Cataclysm date, and that were done after the charge removal commit, as per request on Discord.
=> Make start date and Cataclysm date adjustable

src/activity_actor.cpp, src/character.cpp, src/character.h, src/crafting.cpp, src/do_turn.cpp, tests/char_sight_test.cpp, tests/reading_test.cpp
Bugfixes "Fix fine detail vision modifier"
Port DDA fix: https://github.com/CleverRaven/Cataclysm-DDA/pull/67295
Previously this always made light appear on sidebar as "bright" underground or above ground, which also allowed you to read in complete darkness.
=> Fix fine detail vision modifier

data/json/EraOfDecay/recipes/comestibles/veggy_dishes.json
=> Create veggy_dishes.json and add recipes.

src/options.cpp, src/proficiency.cpp
Добавляем настройку скорости изучения умений
Увеличить контроль игрока над игрой
Провести слияние
Сделать по своему
Думаю идеально подходит для тех, кто считает умения обременяющими
=> скорость изучения умений

data/json/furniture_and_terrain/terrain-roofs.json, data/json/mapgen/cabin.json, data/json/mapgen/farm.json, data/json/npcs/common_chat/TALK_COMMON_OTHER.json, data/json/scenarios.json
Сценарий "безопасное место" теперь безопасен. 
Крыши можно сломать.
Угроза убить нпс с большей вероятностью сделает их враждебными.
Из-за того, что сценарий "безопасное место" немного устарел, он перестал быть безопасным
Сделал крыши ломаемыми так как люблю строить.
Провести слияние
Сделать по своему
Заспавниться в безопасном месте, ударить крышу.
Угрожать нпс
=> Сценарий "безопасное место" теперь безопасен. Крыши можно сломать. Нпс более адекватно относятся к угрозе

data/json/EraOfDecay/items/tools/other.json
=> быстрый багфикс

src/vehicle.cpp
Fixes the vehicle fuel and battery bug where all tanks would be 100% full and all batteries 0%.  Now they are set randomly within given bounds as intended.
int max was being shadowed by float max in an inner block.  Renamed variables to differentiate them.
None.
Played game and noted that the bug was fixed.
None.
=> Fixed vehicle fuel/battery bug.

data/json/itemgroups/books.json, data/json/items/book/spiritual.json
Content "Port new holy books from BN"
Adding new representation to the forks, both for the sake of representation and in case mods wish to call for the new items for recipes or quests.
Added the 4 new books and changed itemgroup. The No religious texts mod was missing so that was not ported. The Catholic bible was already done on DDA's end
None
Trivial JSON changes, should not break savegames or the builds.
https://github.com/cataclysmbnteam/Cataclysm-BN/pull/3841
=> Port new holy books from BN
